name: Build workshop

env:
  GH_REPO: ${{ github.repository }}

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build workshop
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive # Updates the Languages submodule
    
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x
      
    - name: Run workshop bundler
      run: ./workshop_bundler.sh

    - run: mkdir -p output

    - name: Move files
      run: mv Multiplayer/ output/

    - id: get_version
      run: echo "VERSION=$(echo ${{ github.ref_name }})" >> "$GITHUB_OUTPUT"

    - name: Upload mod artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Multiplayer-${{ steps.get_version.outputs.VERSION }}
        path: |
          output/

    - name: Upload GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        VERSION="${{ steps.get_version.outputs.VERSION }}"
        ZIP=$(ls Multiplayer-v*.zip | head -n 1)
        gh release create --repo "$GH_REPO" --target "${{ github.sha }}" \
          --title "$VERSION" \
          --generate-notes \
          "$VERSION" "$ZIP" \
          || gh release upload --repo "$GH_REPO" "$VERSION" "$ZIP" --clobber
